### ISSUE TITLE
Will you support pytorch>1.7.1 ?

### ISSUE THREAD

**Issue by ykk648** [EndlessSora/focal-frequency-loss#3]
Can you tell me the reason and how can I mod codes to support pytorch>1.7.1 ?
For example 1.8.1 ?

**Comment by kjerk** [comment]
I was also looking into doing this transition myself, but like the other poster, am not familiar with the fft methods in Pytorch. In 1.8 the `torch.fft` methods were remove and torch.fft is now a full new module.

https://github.com/pytorch/pytorch/wiki/The-torch.fft-module-in-PyTorch-1.7

Most importantly: the backing code and tensors changed to be complex tensors, and so even if you replace the call to `torch.rfft()`: 
https://github.com/EndlessSora/focal-frequency-loss/blob/27f99aa8429d890a29cd693d41598313aa1a6311/focal_frequency_loss/focal_frequency_loss.py#L48
with something like

```python
return torch.fft.fft(y, dim=2, norm='ortho')
```

Then later the calls to .max() fail:
https://github.com/EndlessSora/focal-frequency-loss/blob/27f99aa8429d890a29cd693d41598313aa1a6311/focal_frequency_loss/focal_frequency_loss.py#L65-L68

**Comment by EndlessSora** [comment]
Thanks all for your interest and suggestions. We have supported PyTorch > 1.7.1 in [this new commit](https://github.com/EndlessSora/focal-frequency-loss/commit/dcaa01ecbfbbd9d8f83f7e5993474e1aa087227c). Please upgrade/reinstall the `focal-frequency-loss` package through `pip` or use the newest code in this repo.

Please close the issue if you find the problem is resolved. Thank you. :)

**Comment by ykk648** [comment]
thx
